### PR TITLE
fix: log drain pricing for self hosted

### LINKED ISSUE #40502: 60$ charging info for log drains still appear in self hosted
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using a self-hosted Supabase instance deployed via Docker, creating a new log drain destination prompts a warning indicating an additional charge of $60 per month. This pricing notification appears even though the instance is self-hosted, which is misleading because users expect such charges only for managed cloud services, not for self-hosted setups.

## To Reproduce

1. Deploy Supabase using the self-hosted Docker setup.
2. Access the Supabase dashboard or management interface.
3. Navigate to Project Settings > Log Drains.
4. Attempt to create a new log drain destination (e.g., a webhook URL).
5. Observe the prompt warning about additional charges ($60 per month).

## Expected behavior

Not showing any extra pricing

## Screenshots

Image

Image

## System information

- OS: Windows
- Browser chrome
Based on the provided Docker Compose configuration for your self-hosted Supabase setup, the versions of the key Supabase components and related services are as follows:

- supabase/studio: 2025.11.10-sha-5291fe3
- kong: 2.8.1
- supabase/gotrue: v2.182.1
- postgrest/postgrest: v13.0.7
- supabase/realtime: v2.63.0
- supabase/storage-api: v1.29.0
- darthsim/imgproxy: v3.8.0
- supabase/postgres-meta: v0.93.1
- supabase/edge-runtime: v1.69.23
- supabase/logflare: 1.22.6
- supabase/postgres: 15.8.1.085
- timberio/vector: 0.28.1-alpine
- supabase/supavisor: 2.7.4

### PR DESCRIPTION
**Pull request by Ziinc**
Hides log drain pricing on self-hosted/cli.

Closes #40502

### CODE REVIEW

File: apps/studio/components/interfaces/LogDrains/LogDrainsEmpty.tsx [hunk 1]
```diff
@@ -22,7 +23,7 @@ export const LogDrainsEmpty = () => {
       label: 'Read our documentation',
       link: 'https://supabase.com/docs/guides/telemetry/log-drains',
     },
-  ]
+  ].filter((item) => IS_PLATFORM && item.title !== 'Pricing')
```
Comment (kemaldotearth) [inline apps/studio/components/interfaces/LogDrains/LogDrainsEmpty.tsx]: This breaks the UI on platform, surely we want to omit it for self hosted or? 

Screenshot 2025-11-17 at 08 44 51

This this might achieve what you're after 👇 

```suggestion
  ].filter((item) => IS_PLATFORM || item.title !== 'Pricing')
```

File: apps/studio/components/interfaces/LogDrains/LogDrainsEmpty.tsx
Comment (kemaldotearth) [inline apps/studio/components/interfaces/LogDrains/LogDrainsEmpty.tsx:1]: As a follow up, you would also need to hide the numbering as it reads `2. Connect to your drain`.

Let's add `IS_PLATFORM && `hidden` to line 51 for the step counter:

```
!IS_PLATFORM && 'hidden'
```

On top of that we can fix the sizing of the box so it's not awkward with skewed content, on Line 45:

```
<Card className={cn('grid grid-cols-1 bg divide-x mb-8', IS_PLATFORM && '@xl:grid-cols-2')}>
```

This makes sure the content fits the box nicely on self-hosted :)

**Review by kemaldotearth — CHANGES_REQUESTED** [review]
Additional fixes...

Line 594 in `log-drains.tsx` to be replaced with:

```
`border-t bg-background-alternative-200 mt-auto py-1.5 ${!IS_PLATFORM && 'hidden'}`
```

and perhaps we want to hide the pricing documentation for self-hosted?

Line 613, add:

```
<SheetFooter className={cn('p-content !mt-0 !flex-row w-full items-center', !IS_PLATFORM ? '!justify-end' : '!justify-between')}>
```

Line 614 of the same file, add:

```
 <span className={cn('text-sm text-foreground-light', !IS_PLATFORM && 'hidden')}>
```

File: apps/studio/components/interfaces/LogDrains/LogDrainsEmpty.tsx
Comment (Ziinc) [reply apps/studio/components/interfaces/LogDrains/LogDrainsEmpty.tsx:1]: adjusted

**Comment by Ziinc** [comment]
Should preserve linking to documentation.

**Review by kemaldotearth — APPROVED** [review]
Thanks for sorting the self hosted stuff :) :shipit:
