### PR TITLE
Fix SQL rename modal not rendering description properly

### LINKED ISSUE #5838: The query description isn't stored
# Bug report

## Describe the bug

The modal window for renaming queries provides a way to add a description to the query. However, not only is that description not shown anywhere in the UI, but it's not even persisted, as the user can observe by attempting to modify it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `https://app.supabase.io/project/<project-id>/sql`
2. Create a new query
3. Rename the query and give it a description
4. Try to find the description anywhere in the UI
5. Try to modify the description by renaming the query again

## Expected behavior

The query description is prominently displayed in the UI and persisted across renames.

## Screenshots

Here's the modal dialog in question:

rename query dialog

## System information

- OS: Windows
- Browser (if applies): Latest Chrome

### PR DESCRIPTION
**Pull request by joshenlim**
Resolves https://github.com/supabase/supabase/issues/5838

### CODE REVIEW

File: studio/components/to-be-cleaned/SqlEditor/RenameQuery.js [hunk 1]
```diff
@@ -56,7 +57,7 @@ const RenameQuery = observer(({ tabId, onComplete, visible, onCancel }) => {
         validateOnBlur
         initialValues={{
           name: model ? model.name : '',
-          description: model ? model.desc : '',
+          desc: model ? model.desc : '',
```
Comment (MildTomato) [inline studio/components/to-be-cleaned/SqlEditor/RenameQuery.js:60]: lol 🙈

**Review by MildTomato — APPROVED** [review]
