### PR TITLE
fix: extension links

### LINKED ISSUE #14990: Docs: Extension search returns incorrect links
## Describe the bug

The [extensions search component](https://supabase.com/docs/guides/database/extensions#full-list-of-extensions) in the docs return incorrect links for some of the extensions.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://supabase.com/docs/guides/database/extensions#full-list-of-extensions
2. Type 'cron' in the extension search box
3. Click on the `pg_cron` card
4. See 404 error

## Expected behavior

We expect the links to navigate to valid pages. In the above example, the real page lives on `/pgcron`, not `pg_cron`.

## Additional context

There are a number of other extensions that have the same problem. We're pretty inconsistent with naming (ie. some extensions use snake case, others are all lowercase with no separator).

**At a minimum:** Fix the broken links
**Also consider:** If it is worth bringing some consistency to our extension names. Will need to add redirects in `www` if we decide to rename URL paths.

### PR DESCRIPTION
**Pull request by mdjohns**
## What kind of change does this PR introduce?

Bug fix.

## What is the current behavior?
(See #14990)

On [the Postgres Extensions Overview page](https://supabase.com/docs/guides/database/extensions#full-list-of-extensions), not all extensions have links, and some links are incorrect.
 

## What is the new behavior?

Unneeded extensions have been removed and all extensions now have the appropriate link (externally or to one of our guides).

(closes #14990)

### CODE REVIEW

File: apps/docs/components/Extensions.tsx [hunk 1]
```diff
@@ -98,8 +98,8 @@ export default function Extensions() {
                   passHref
                   href={`${
                     extension.link
-                      ? `/guides/database/extensions/${extension.name}`
-                      : '/guides/database/extensions#full-list-of-extensions'
```
Comment (mdjohns) [inline apps/docs/components/Extensions.tsx:102]: Only external links will have this property. If it exists, use that. Otherwise, use a relative link to our docs using the extension's name.

File: apps/docs/components/Extensions.tsx [hunk 2]
```diff
@@ -3,14 +3,14 @@ import React, { useState } from 'react'
 import { GlassPanel, IconLink, IconX, Input } from 'ui'
 import extensions from '../data/extensions.json'
 
-type extension = {
```
Comment (mdjohns) [inline apps/docs/components/Extensions.tsx:6]: Did a few tiny TypeScript cleanups, hope that's okay!

File: apps/docs/pages/guides/database/extensions/pg_cron.mdx [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import Layout from '~/layouts/DefaultGuideLayout'
 
 export const meta = {
-  id: 'pgcron',
```
Comment (mdjohns) [inline apps/docs/pages/guides/database/extensions/pg_cron.mdx:4]: Renamed any files that did not match the existing name in `extensions.json` and added the appropriate redirect.

File: apps/docs/components/Extensions.tsx (hunk 1 above)
Comment (gregnr) [reply apps/docs/components/Extensions.tsx:102]: Thoughts on making `link` required and including both internal and external URLs in `extensions.json`? Feels like we could benefit from the simplicity of less moving parts (and less opportunities to accidentally link to a broken URL).

Worth noting we will likely share `extensions.json` with the dashboard to do something similar (after this PR is merged):
#15431

Internal links could be relative:
```json
{
  "name": "pg_cron",
  "comment": "Job scheduler for PostgreSQL",
  "link": "/guides/database/extensions/pg_cron",
  "tags": ["Utility"]
}
```

**Review by gregnr — COMMENTED** [review]
Hey @mdjohns, great work here! Sorry for the delay. Just had one comment but otherwise we should be good to merge.

File: apps/docs/components/Extensions.tsx (hunk 1 above)
Comment (mdjohns) [reply apps/docs/components/Extensions.tsx:102]: Makes sense to me to be more explicit! 

I'll make that change tonight when I resolve the merge conflicts.

**Review by gregnr — APPROVED** [review]
