### PR TITLE
Fix/enable queue rest management pqmq versions

### LINKED ISSUE #39656: Enabling "Expose Queues via PostgREST" fails on newest Postgres Version due to pgmq.read parameter change
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Enabling "Expose Queues via PostgREST" fails on newest Postgres Version because it expects a function with 3 parameters, but the function takes 4  (text, integer, integer, json)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable Queues Integration
2. try to enable "Expose Queues via PostgREST"
4. See error:
`Failed to toggle queue exposure via PostgREST: function pgmq.read(text, integer, integer) does not exist`

## Expected behavior

It should create the correct public schema

### PR DESCRIPTION
**Pull request by awaseem**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Bug fix able to change the toggle for "Expose Queues via PostgREST"

Fixes: https://github.com/supabase/supabase/issues/39656

## What is the current behavior?

You can't toggle because the new version of PGMQ has a function change

## What is the new behavior?

Be able to toggle and untoggle changes

## Additional context

How to test:
- Enable the queues extension
- Go to settings and toggle the "Expose Queue via PostgREST" 
- It should save without errors

### CODE REVIEW

File: apps/studio/data/database-queues/constants.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+export const PGMQ_EXTENSION_NAME = 'pgmq' as const
+
+export const DEFAULT_PGMQ_VERSION = '1.5.1' as const
+export const SUPPORTED_PGMQ_VERSIONS = ['1.4.4', DEFAULT_PGMQ_VERSION] as const
```
Comment (ivasilov) [inline apps/studio/data/database-queues/constants.ts]: It won't work with `1.4.3` version, right? There's no need for a hard-coded default version (which will also change in the future). Condition should be just `version < 1.5.0`.

Comment (awaseem) [reply apps/studio/data/database-queues/constants.ts]: Do we have a utility that compares semvar?

Comment (awaseem) [reply apps/studio/data/database-queues/constants.ts]: Created one instead

**Review by ivasilov — APPROVED** [review]
