### PR TITLE
fix: change nextjs connect methods to match new ssr api

### LINKED ISSUE #27666: Update docs for Next.js
# Improve documentation

## Link 

Docs from the homepage inside dashboad for connecting Next.js with Supabase
image

## Describe the problem

Gives a warning about declaration of some methods
image

## Describe the improvement

Update the Next.js code or/and add option to swich between verstions of package

### PR DESCRIPTION
**Pull request by charislam**
The latest version of the SSR package changes the recommended API for defining cookie methods (see [docs](https://supabase.com/docs/guides/auth/server-side/nextjs?queryGroups=router&router=app)). Updating the connect methods to match.

### CODE REVIEW

File: apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx [hunk 1]
```diff
@@ -64,26 +64,11 @@ export const createClient = (cookieStore: ReturnType<typeof cookies>) => {
...
-        remove(name: string, options: CookieOptions) {
-          try {
-            cookieStore.set({ name, value: "", ...options });
-          } catch (error) {
-            // The \`delete\` method was called from a Server Component.
-            // This can be ignored if you have middleware refreshing
-            // user sessions.
-          }
+        setAll(cookiesToSet) {
+          cookiesToSet.forEach(({ name, value, options }) => cookieStore.set(name, value, options))
```
Comment (ivasilov) [inline apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx:71]: Should this be in a `try/catch` block? Asking because the previous code and the docs code have it.

File: apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx [hunk 2]
```diff
@@ -125,50 +110,23 @@ export const createClient = (request: NextRequest) => {
...
-              headers: request.headers,
-            },
-          });
-          response.cookies.set({
-            name,
-            value: "",
-            ...options,
-          });
+        setAll(cookiesToSet) {
+          cookiesToSet.forEach(({ name, value, options }) => request.cookies.set(name, value))
```
Comment (ivasilov) [inline apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx:117]: `try/catch` block?

File: apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx (hunk 1 above)
Comment (charislam) [reply apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx:71]: Yep good catch! It was missing in the first rewrite of the docs, and we had to edit it back in

File: apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx (hunk 2 above)
Comment (charislam) [reply apps/studio/components/interfaces/Home/Connect/content/nextjs/app/supabasejs/content.tsx:117]: not for middleware, since cookies can actually be set from middleware

**Review by MildTomato — APPROVED** [review]
@charislam assuming all the code changes are correct.
