### PR TITLE
Chore/fix hooks sheet

### LINKED ISSUE #29741: Layout issue when adding auth hook
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running on a smaller screen (I am on a 15" Macbook pro 1440 x 900 screen), when trying to add an auth hook, the side modal is cut off vertically and does not show the submit or cancel button at the bottom (the screen nor modal can be scrolled vertically)

Screenshot below

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the dashboard on a smaller screen
2. Go to Authentication -> Hooks
3. Click add a new hook
4. Notice the form buttons at the bottom of the modal are not reachable (other than tabbing with keyboard and guessing which one has received the focus.

## Expected behavior

Buttons should be visible, either all of the time, or the modal should be scrollable.

## Screenshots

image

## System information

- OS: macOS
- Browser : chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

### PR DESCRIPTION
**Pull request by saltcod**
fixes https://github.com/supabase/supabase/issues/29741

### CODE REVIEW

File: apps/studio/components/interfaces/Auth/Hooks/CreateHookSheet.tsx [hunk 1]
```diff
@@ -290,196 +290,199 @@ export const CreateHookSheet = ({
...
-                      onCheckedChange={field.onChange}
-                      disabled={field.disabled}
-                    />
-                  </FormControl_Shadcn_>
-                </FormItemLayout>
-              )}
-            />
-            <Separator />
-            {httpsAuthHooksEnabled && (
+        <div className="overflow-auto flex-grow">
```
Comment (saltcod) [inline apps/studio/components/interfaces/Auth/Hooks/CreateHookSheet.tsx:293]: looks like lots of changes here, but view without whitespace — only added this wrapping div

File: apps/studio/components/interfaces/Auth/Hooks/AddHookDropdown.tsx [hunk 2]
```diff
@@ -78,16 +78,17 @@ export const AddHookDropdown = ({
...
             <DropdownMenuItem key={h.title} onClick={() => onSelectHook(h.title)}>
               {h.title}
             </DropdownMenuItem>
           ))}
         </div>
+
         {nonEnterpriseHookOptions.length > 0 && <DropdownMenuSeparator />}
 
-        <div className="bg-surface-200 p-1 -mt-2">
+        <div className="bg-surface-200 -mt-1">
```
Comment (MildTomato) [inline apps/studio/components/interfaces/Auth/Hooks/AddHookDropdown.tsx:91]: ?

File: apps/studio/components/interfaces/Auth/Hooks/CreateHookSheet.tsx (hunk 1 above)
Comment (ivasilov) [reply apps/studio/components/interfaces/Auth/Hooks/CreateHookSheet.tsx:293]: Replace this div with `SheetSection`. You can view the changes without whitespace [here](https://github.com/supabase/supabase/pull/29746/files?diff=split&w=1)

**Review by ivasilov — APPROVED** [review]
