### PR TITLE
Chore/fix sotrage explorer delete files clears parent folder if empty

### LINKED ISSUE #4493: Parent folder is deleted when deleting empty sub folder
# Bug report

## Describe the bug

The .emptyFolderPlaceholder that is created when creating a new "folder" gets deleted when an other item is added.

But there is a problem is a create multiple empty subfolders.

Lets say i want to upload a file to my `Avatar` bucket in the following location: `/users/images/userAvatar.jpg`

I will create a folder `user` which will contain the `.emptyFolderPlaceholder` until i create the `images` and finally upload the `userAvatar.jpg`.

I currently have something like this:

Avatar
     /users
            /images
                   /userAvatar.jpg

Here is the problem, if i delete `userAvatar.jpg`, `images` and `users` folders will be deleted because the do not contain the `.emptyFolderPlaceholder` anymore.

## Expected behavior

We should do the same `.emptyFolderPlaceholder` logic, but backward when deleting an item in a folder.

Meaning that if i delete an item in a folder and this item is the last item, a `.emptyFolderPlaceholder` should be added because deleting the file.

### PR DESCRIPTION
**Pull request by joshenlim**
Resolves https://github.com/supabase/supabase/issues/4493

2 parts to this
- After deleting a folder, if the parent folder is empty as a result of that, reinstate the `.emptyFolderPlaceholder`
- After deleting files, if the parent folder of the files are empty as a result of that, reinstate the `.emptyFolderPlaceholder`

### CODE REVIEW

File: studio/localStores/storageExplorer/StorageExplorerStore.js [hunk 1]
```diff
@@ -291,6 +294,8 @@ class StorageExplorerStore {
       return this.removeTempRows(columnIndex)
     }
 
+    this.updateFolderAfterEdit(formattedName, columnIndex)
```
Comment (joshenlim) [inline studio/localStores/storageExplorer/StorageExplorerStore.js:297]: Shifted it up a level as there's an awkward pause from hitting "Enter" until the folder is ready as we're uploading the placeholder file.

We can just let the user access the folder immediately without waiting for the placeholder file to upload finish

File: studio/localStores/storageExplorer/StorageExplorerStore.js [hunk 2]
```diff
@@ -993,11 +1007,32 @@ class StorageExplorerStore {
...
+    }
+  }
+
   deleteFolder = async (folder) => {
+    const isDeleteFolder = true
     const files = await this.getAllItemsAlongFolder(folder)
-    const showFilesDeleteToast = false
+    await this.deleteFiles(files, isDeleteFolder)
+
+    const parentFolderPrefix = this.openedFolders.map((folder) => folder.name).join('/')
```
Comment (joshenlim) [inline studio/localStores/storageExplorer/StorageExplorerStore.js:1029]: the empty folder validation has to run separately from that within deleteFiles, and deleteFolder only need to check it's parent folder, and not the parent folder of each individual file within the folder

**Review by phamhieu — APPROVED** [review]
Lgtm!
