### PR TITLE
fix(studio): storage policy editor auto-selects select when update or delete is chose

### LINKED ISSUE #40905: Adding a new policy to a bucket the "allowed operations" aren't accurately depicted
# Bug report

I confirm this is a bug with Supabase, not with my own application. 

## Describe the bug

When Adding a new policy to a bucket, when you click the following. SELECT, INSERT, UPDATE, or DELETE, the respective operations that you should be able to use in the client library are highlighted automatically. They are correctly highlighted for SELECT and INSERT but they are not correctly highlighted for UPDATE and DELETE.

SELECT: download, list, createSignedUrl, createdSignedUrls, getPublicUrl
INSERT: upload, getPublicUrl
UPDATE: getPublicUrl
DELETE: getPublicUrl

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Storage / Files / [create a bucket and click that bucket ] 
2. Click on 'Policies'
3. Click on 'New Policy' for that respective bucket
4. Click 'For full customization....'
5. Check 'DELETE'
7. See that it only highlighted 'getPublicUrl' and not 'remove'

8. Now uncheck 'DELETE' and check 'UPDATE'
9. See that it only highlighted 'getPublicUrl' and not 'move' or 'copy'

## Screenshots
Missing items for DELETE
Image

Missing items for UPDATE
Image

Works for SELECT
Image

Works for INSERT
Image

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

### LINKED ISSUE #40923: Bug: Storage policy “allowed operations” not correctly highlighted for UPDATE and DELETE
## Description
When creating a new Storage policy, selecting **UPDATE** or **DELETE** does not highlight the correct client library operations. Only `getPublicUrl` appears, while the expected operations (`move`, `copy`, `remove`) are missing.

## Expected Behavior
- **UPDATE** should highlight: `copy`, `move`, `getPublicUrl`
- **DELETE** should highlight: `remove`, `getPublicUrl`

(These operations require `SELECT` + the respective write permission.)

## Actual Behavior
- UPDATE → only `getPublicUrl` highlights
- DELETE → only `getPublicUrl` highlights

## Steps to Reproduce
1. Go to **Storage → Files → [Your bucket]**
2. Open **Policies**
3. Click **New Policy**
4. Select **For full customization**
5. Check **UPDATE** or **DELETE**
6. Observe that only `getPublicUrl` is highlighted

## Notes
- The internal mapping is correct:
  - update/move require: `['SELECT', 'UPDATE']`
  - remove requires: `['SELECT', 'DELETE']`
- If you manually enable **SELECT** alongside UPDATE or DELETE, the correct operations highlight.
- This suggests the UI may need to automatically select **SELECT** when UPDATE or DELETE is toggled.

## Environment
- **Supabase Dashboard:** latest
- **Browser:** any

### PR DESCRIPTION
**Pull request by 7ttp**
## what kind of change does this pr introduce?

bug fix

## what is the current behavior?

update/delete doesnt highlight anything. 

## what is the new behavior?

when selecting update or delete, the select permission is automatically selected since these operations require it. when deselecting select, update and delete are automatically deselected to maintain consistency.
this ensures the correct client library methods are highlighted based on the selected permissions.

fixes #40923

### CODE REVIEW

**Comment by 7ttp** [comment]
@kallebysantos @mandarini please review when available!

**Comment by awaseem** [comment]
@7ttp This is awesome and apperciate you taking the time to address this. Its a bit confusing to the user when update and delete is selected and it auto checks `select`. Would it be possible to add a a message under to explain why the autoselection is happening?

**Comment by 7ttp** [comment]
> @7ttp This is awesome and apperciate you taking the time to address this. Its a bit confusing to the user when update and delete is selected and it auto checks `select`. Would it be possible to add a a message under to explain why the autoselection is happening?

Got it! I’ll add a little note under it to explain why select gets autochecked. Updating it now

File: apps/studio/components/interfaces/Storage/StoragePolicies/StoragePoliciesEditor.tsx [hunk 1]
```diff
@@ -70,6 +73,11 @@ const PolicyAllowedOperations = ({ allowedOperations = [], onToggleOperation = (
             checked={allowedOperations.includes('DELETE')}
           />
         </div>
+        {hasUpdateOrDelete && (
+          <p className="text-sm text-foreground-lighter mt-3">
+            SELECT has been auto selected as UPDATE and DELETE require it
```
Comment (kallebysantos) [inline apps/studio/components/interfaces/Storage/StoragePolicies/StoragePoliciesEditor.tsx]: Hi @7ttp 💚
May you pls, wrap the `SELECT`, `UPDATE` and `DELETE` in a code syntax style? Just like I'm doing in this comment.

I believe you can do it by adding `<code>` around these titles.

Comment (awaseem) [reply apps/studio/components/interfaces/Storage/StoragePolicies/StoragePoliciesEditor.tsx]: +1 this, let's wrap it

Comment (7ttp) [reply apps/studio/components/interfaces/Storage/StoragePolicies/StoragePoliciesEditor.tsx]: Aight sure!

**Review by kallebysantos — APPROVED** [review]
I did improve a little the code style to match as other parts from studio.

<details>

image

</details>

Looks Good to me!! Thanks @7ttp 💚

**Review by awaseem — APPROVED** [review]
LGTM tested on staging and looks good!
