### PR TITLE
fix: studio editor enum

### LINKED ISSUE #11757: Table Editor: Grid enum dropdown selection is not showing the dropdown
# Bug report

## To Reproduce
1. Create the `countries` table via the SQL editor quick start scripts
2. Open the `countries` table in the table editor
3. On any row, double click on the `continent` column to attempt to change the value
4. The listbox does not show up (or is portalled incorrectly)

image

## Expected behavior

The listbox should be rendered correctly showing the possible options for the enumerated type

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Supabase Studio > Table Editor > Enum Select

## What is the current behavior?

Currently the `Listbox` does not show the dropdown values in the editor

## What is the new behavior?

Changed the `Listbox` to a `Select` and the enum values now appear:

https://user-images.githubusercontent.com/22655069/213496446-c8cb9632-b2e3-403e-a10b-31d678a3fe82.mov

## Additional context

Closes #11757

### CODE REVIEW

**Review by alaister — CHANGES_REQUESTED** [review]
Thanks, @Hallidayo!

Would it be possible to have the default value of the Select be the currently selected option? I think it feels a little strange when you go to edit a value and it says `NULL`:


https://user-images.githubusercontent.com/10985857/213601949-ecbc9b22-4760-4fb4-b31e-aeb9a392e2a5.mov

**Review by Hallidayo — COMMENTED** [review]
Hi @alaister - just changed this now:


https://user-images.githubusercontent.com/22655069/213691946-c504a193-14d8-45f6-91a9-576195befd63.mov

File: studio/components/grid/components/editor/SelectEditor.tsx [hunk 1]
```diff
@@ -19,11 +19,11 @@ export function SelectEditor<TRow, TSummaryRow = unknown>({
 
   const value = row[column.key as keyof TRow] as unknown as string
 
-  function onChange(value: string) {
+  function onChange(value: any) {
```
Comment (alaister) [inline studio/components/grid/components/editor/SelectEditor.tsx:22]: Small nit: should this be called `event` instead of `value`? It seems a little odd to be saying `value.target.value` below.

Comment (Hallidayo) [reply studio/components/grid/components/editor/SelectEditor.tsx]: @alaister - Just renamed the `value` parameter as that does look odd.

Also fixed an issue where the `NULL` option was not saving when selected.

File: studio/components/grid/components/editor/SelectEditor.tsx [hunk 2]
```diff
@@ -19,11 +19,12 @@ export function SelectEditor<TRow, TSummaryRow = unknown>({
 
   const value = row[column.key as keyof TRow] as unknown as string
 
-  function onChange(value: string) {
-    if (!value || value == '') {
+  function onChange(event: any) {
+    debugger
+    if (!event.target.vaue || event.target.value == '') {
```
Comment (alaister) [inline studio/components/grid/components/editor/SelectEditor.tsx:24]: Small typo: `!event.target.vaue` -> `!event.target.value`

File: studio/components/grid/components/editor/SelectEditor.tsx (hunk 1 above)
Comment (alaister) [reply studio/components/grid/components/editor/SelectEditor.tsx]: Nice one! Just one small typo left and then we'll get this merged – thank you!

File: studio/components/grid/components/editor/SelectEditor.tsx (hunk 2 above)
Comment (Hallidayo) [reply studio/components/grid/components/editor/SelectEditor.tsx]: @alaister - typo just fixed

**Review by alaister — APPROVED** [review]
Thanks, @Hallidayo!
