### PR TITLE
Fix: updated RLS to use messages instead of formatted error

### LINKED ISSUE #40282: Not showing error message in "Error running SQL query" toast
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When creating a RLS policy for a table and trying to save the Error running SQL query" toast will appear but no error message is shown. I can see the error in the response (network tab). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'Authentications'
2. Click on 'Policies'
3. Scroll down to 'Create policy'
4. Choose a Policy Template (Make sure it cause an error)
5. The Error toast will appear with no error message

## Expected behavior

The error message should be shown in error toast.

## Screenshots

Image

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

### PR DESCRIPTION
**Pull request by awaseem**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

Yes

## What kind of change does this PR introduce?

RLS error messages were not showing up, this fixes it to use the message string

## What is the current behavior?

No error messages

## What is the new behavior?

Error messages when modify RLS through editor

## Additional context

- closes #40282

### CODE REVIEW

File: apps/studio/data/sql/execute-sql-mutation.ts [hunk 1]
```diff
@@ -16,7 +16,6 @@ export type QueryResponseError = {
   code: string
   message: string
   error: string
-  formattedError: string
```
Comment (awaseem) [inline apps/studio/data/sql/execute-sql-mutation.ts:19]: This is not used anywhere. Its kinda strange, we as a team decided to move off this implicitly. See investigation notes here: 

>Wow I went down a deep rabbithole. So formattedError is only used in a single place which is this prompt. Also all the errors in the SQL editor or event the cmd E sql editor don't have formatting. It seems everyone in the code base moved of formatted error

> It only works for self hosted because we handle it in the API, the fix is simple


>N one of them have formatting in platform or self hosted, I guess this just become the default now

**Review by charislam — APPROVED** [review]
Tested for both self-hosted and hosted
