### PR TITLE
Fix using camel case enum from public schema erroring out in ColumnEditor

### LINKED ISSUE #31260: Uppercase enums do not work
Enums with an uppercased name do not work in the dashboard, but lowercase ones do.

### PR DESCRIPTION
**Pull request by joshenlim**
Resolves https://github.com/supabase/supabase/issues/31260

- Removed escaped double quotes for camel cased enums when displaying them in the UI
- Stripe double quotes for enum types in the public schema only

### CODE REVIEW

File: apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnType.tsx [hunk 1]
```diff
@@ -67,8 +67,11 @@ const ColumnType = ({
...
 }: ColumnTypeProps) => {
   const [open, setOpen] = useState(false)
-  // @ts-ignore
-  const availableTypes = POSTGRES_DATA_TYPES.concat(enumTypes.map((type) => type.format))
+  const availableTypes = POSTGRES_DATA_TYPES.concat(
+    enumTypes.map((type) =>
+      type.schema === 'public' ? type.format.replaceAll('"', '') : type.format
+    )
+  )
   const isAvailableType = value ? availableTypes.includes(value) : true
```
Comment (alaister) [inline apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnType.tsx:75]: Just to confirm, this `value` doesn't need a `.replaceAll('"', '')` as well?

Comment (joshenlim) [reply apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnType.tsx:75]: value here should be okay since its a passed prop
- When selecting a new column type, we'd "sanitize" it when we selected the option, so value here will have the double quotes stripped already if needed
- When viewing a column's type though, i noticed that if the enum is not from the public schema, the user will not be able to edit the column, but i feel like this needs to be fixed on pg-meta's end? it seems like the type of the column does not contain the type's schema
image

Comment (joshenlim) [reply apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnType.tsx:75]: ^ this bug is an existing issue though, so probably can address separately

Comment (joshenlim) [reply apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnType.tsx:75]: hmm one sec - i noticed this can be fixed from dashboard, not pgmeta

Comment (joshenlim) [reply apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnType.tsx:72]: okay updated this, should be fixed now 😄

**Review by alaister — APPROVED** [review]
LGTM!

- Tested on preview
