### PR TITLE
fix: Unable to export data from the table to CSV

### LINKED ISSUE #19275: Export CSV not working on local development instance
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On the Studio URL: http://127.0.0.1:54323, in a table, I tried to export table data by clicking on `Export as CSV` but nothing happened.
 
## To Reproduce

1. Run a local development Supabase instance and go to the Studio URL: http://127.0.0.1:54323
2. Make sure you have a table with some rows and data in them
3. In the left side menu, click on the arrow next to the table name and click `Export as CSV`
4. See? Nothing happens, no download, no error displayed. 

## Expected behavior

A CSV file should be downloaded. I tried on the hosted Supabase instance and it works as expected. 

## System information

- OS: macOS 13.2.1 Ventura
- Browser (if applies) Arc and Firefox

image

### PR DESCRIPTION
**Pull request by tranhoangvuit**
## What kind of change does this PR introduce?

fixes: https://github.com/supabase/supabase/issues/19275

## What is the current behavior?

Unable export table to CSV not working on local development

## What is the new behavior?

Can export table to CSV not working on local development

## Additional context

Because on local development we can send empty connection string to query data, so in this PR we just make it like option on `PLATFORM`

image

### CODE REVIEW

File: apps/studio/components/layouts/TableEditorLayout/EntityListItem.tsx [hunk 1]
```diff
@@ -39,6 +40,7 @@ const EntityListItem = ({ id, projectRef, item: entity, isLocked }: EntityListIt
   const { ui } = useStore()
   const { project } = useProjectContext()
   const snap = useTableEditorStateSnapshot()
+  console.log(snap)
```
Comment (saltcod) [inline apps/studio/components/layouts/TableEditorLayout/EntityListItem.tsx:43]:
```suggestion
```

**Review by saltcod — APPROVED** [review]
