### PR TITLE
fix(studio): handle null db_pool when creating api schema

### LINKED ISSUE #41511: Failed to create and expose API schema: db_pool: Expected number, received null
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Failed to create and expose API schema: db_pool: Expected number, received null

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Project Settings > Data API
2. Under Data API Settings > Click on Harden Data API
3. Click and expand "Create a custom api schema and expose it"
4. Click on "Create and expose schema to Data API" button
5. See error

## Screenshots

Image

## System information

- OS: macOS
- Browsers: Firefox, Chrome, Safari, Edge

### PR DESCRIPTION
**Pull request by 7ttp**
Clicking "Create and expose schema to Data API" fails with error:

image

The postgrest config can return `db_pool` as null,
 but the mutation was passing it directly to the API which expects a number. 
This fix omits `db_pool` from the request body when null,
allowing it to use its default value.

- closes https://github.com/supabase/supabase/issues/41511

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved API settings configuration handling to properly manage database pool parameters, ensuring more accurate and reliable API schema mutations.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/studio/data/api-settings/create-and-expose-api-schema-mutation.ts [hunk 1]
```diff
@@ -31,14 +31,17 @@ grant usage on schema api to anon, authenticated;
   await executeSql({ projectRef, connectionString, sql })
 
   const { db_extra_search_path, db_pool, db_schema, max_rows } = existingPostgrestConfig
+
+  const body: { max_rows: number; db_extra_search_path: string; db_schema: string; db_pool?: number } = {
```
Comment (kallebysantos) [inline apps/studio/data/api-settings/create-and-expose-api-schema-mutation.ts]: I think that is possible to extend from API types instead of defining it inline here.

File: apps/studio/data/api-settings/create-and-expose-api-schema-mutation.ts [hunk 2]
```diff
@@ -11,7 +11,7 @@ export type CreateAndExposeAPISchemaVariables = {
   projectRef: string
   connectionString?: string | null
   existingPostgrestConfig: {
-    db_pool: any
+    db_pool: number | null
```
Comment (kallebysantos) [inline apps/studio/data/api-settings/create-and-expose-api-schema-mutation.ts]: Maybe we should follow the same type def as `connectionString` ?
like:
```ts
db_pool?: number | null // with '?'
```

**Review by kallebysantos — COMMENTED** [review]
Hi @7ttp 💚
Thanks for contributing!

**Review by kallebysantos — APPROVED** [review]
Hi @7ttp 💚
Thanks for your contribution, LGMT!!
I tested it both at Platform (current) as well on Staging (your fix) environment.

<details>
<summary>Platform ❌</summary>

https://github.com/user-attachments/assets/ce45ca82-2f1f-42f4-aba4-806ab8209044

</details>

<details>
<summary>Staging - Your fix ✅</summary>

https://github.com/user-attachments/assets/a4e75794-9a03-424f-b4f4-43b3a325eb18

</details>

**Review by jordienr — APPROVED** [review]
