### PR TITLE
Chore/14432 fix project dropdown

### LINKED ISSUE #14432: Studio returns 404 when switching projects after running a log query
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you try to switch to another project **after** running a log query, a 404 error page is displayed.

## To Reproduce

1. Go to "Logs Explorer" of some project. `https://app.supabase.com/project/<project-id>/logs/explorer`
2. Click on "Run" to execute the default "Last 24 hours" query.
3. Try to switch to another project using the toolbar menu.
4. A 404 error page is displayed because the link points to `https://app.supabase.com/project/<project-id>/logs` (missing `/explorer`)

## Expected behavior

The toolbar project switch points to the "Logs Explorer" view of each project correctly, as it does before clicking on the "Run" button.

## System information

- OS: macOS.
- Browser: Chrome.

### PR DESCRIPTION
**Pull request by saltcod**
— Fix project dropdown on logs/explorer urls with query string at the end 
— adds current item state to project dropdown, currently missing

Fixes https://github.com/supabase/supabase/issues/14432

### CODE REVIEW

File: studio/components/layouts/ProjectLayout/LayoutHeader/ProjectDropdown.tsx [hunk 1]
```diff
@@ -15,9 +15,16 @@ import { IS_PLATFORM, PROJECT_STATUS } from 'lib/constants'
 // highest common route with just projectRef in the router queries.
 
 const sanitizeRoute = (route: string, routerQueries: ParsedUrlQuery) => {
-  let queryArray = Object.entries(routerQueries)
+  const queryArray = Object.entries(routerQueries)
+
   if (queryArray.length > 1) {
-    return route.split('/').slice(0, 4).join('/')
+    // account for query string, if exists (example: /logs/explorer?q=select...)
+    const hasQueryString = queryArray.filter(([key]) => key === 'q').length > 0
```
Comment (gregnr) [inline studio/components/layouts/ProjectLayout/LayoutHeader/ProjectDropdown.tsx:22]: `some()` works good for this:
```suggestion
    const hasQueryString = queryArray.some(([key]) => key === 'q')
```

File: studio/components/layouts/ProjectLayout/LayoutHeader/ProjectDropdown.tsx [hunk 2]
```diff
@@ -15,9 +15,16 @@ import { IS_PLATFORM, PROJECT_STATUS } from 'lib/constants'
...
+
+    return route
+      .split('/')
+      .slice(0, hasQueryString ? 5 : 4)
```
Comment (gregnr) [inline studio/components/layouts/ProjectLayout/LayoutHeader/ProjectDropdown.tsx:26]: nit: hard coded numbers feel brittle... if we are removing the last directory in the path, might consider:
```suggestion
      .slice(0, -1)
```

**Review by gregnr — APPROVED** [review]

File: studio/components/layouts/ProjectLayout/LayoutHeader/ProjectDropdown.tsx (hunk 2 above)
Comment (saltcod) [reply studio/components/layouts/ProjectLayout/LayoutHeader/ProjectDropdown.tsx:26]: Yeah it is brittle Greg, but not sure of a way around it. The other alternative is baking logic in for just the logs explorer pages with query strings. 

Your .slice(0, -1) works but still doesn't account for when logs explorer pages have query strings:

CleanShot 2023-05-23 at 15 39 54@2x
