### PR TITLE
Delete bucket policies when buckets are deleted

### LINKED ISSUE #4600: Bucket Policy Doesn't Delete
# Bug report
Bucket Policy doesn't delete
## Describe the bug
I deleted all buckets and database tables. I ran the UserManagement Starter SQL query and got this error
policy "Anyone can upload an avatar." for table "objects" already exists

## To Reproduce
Delete the avatars bucket. Run the User Management Starter SQL

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

Create a "new" bucket called avatars with all policies in place

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

### PR DESCRIPTION
**Pull request by joshenlim**
Clears policies related to a bucket after deleting a bucket

Resolves https://github.com/supabase/supabase/issues/4600 and https://github.com/supabase/supabase/issues/2110

### CODE REVIEW

File: studio/components/to-be-cleaned/Storage/StorageExplorer/StorageExplorer.js [hunk 1]
```diff
@@ -207,9 +206,6 @@ const StorageExplorer = observer(({ bucket }) => {
     if (selectedItemsToDelete.length === 1) {
       const [itemToDelete] = selectedItemsToDelete
       switch (itemToDelete.type) {
-        case STORAGE_ROW_TYPES.BUCKET:
```
Comment (joshenlim) [inline studio/components/to-be-cleaned/Storage/StorageExplorer/StorageExplorer.js:210]: the very first UI had buckets within the explorer itself, i think i forgot to remove this

**Review by phamhieu — APPROVED** [review]
