### PR TITLE
fix: related articles list showing current article

### LINKED ISSUE #15484: Filter Related list to not show current blog post
supabase.com/blog/[post] is recommending the current post in the Related Posts sidebar. We should filter this list to not include the current post.

Example post
https://supabase.com/blog/chatgpt-plugins-support-postgres

Showing up in the sidebar
CleanShot 2023-06-30 at 13 18 55@2x

### PR DESCRIPTION
**Pull request by ddanielcruzz**
## What kind of change does this PR introduce?

Bug fix

fixes https://github.com/supabase/supabase/issues/15484

## What is the current behavior?

supabase.com/blog/[post] is recommending the current post in the Related Posts sidebar.

## What is the new behavior?

supabase.com/blog/[post] no longer recommends current post

## Additional context

I also improved a little bit the type safety of the page 🦺

#### Before
Screenshot 2023-07-01 at 1 42 30

#### After
Screenshot 2023-07-01 at 1 43 20

### CODE REVIEW

**Comment by ddanielcruzz** [comment]
@kamilogorek Thanks for catching that! I updated `getSortedPosts` to use an object argument rather than positional arguments to make it easier to add new ones. Let me know if this PR needs more changes 😄

**Comment by kamilogorek** [comment]
LGTM! Nice optimization that can be applied in the future is to reduce the number of iterations throughout this function. Right now it's doing quite a lot of redundant operations, which can add up if there're thousands of posts in the future.

Other than reading dir and each files content, it currently:
- maps over each file
- spreads everything into `sortedPosts`
- sorts (btw. `sortedPosts = sortedPosts.sort` is redundant as sort is in-place)
- filters first time
- filters second time
- slices

It's 5 full array iterations. All of this could be done in 2 passes instead. Single iteration + sorting.

```js
const posts = [];
for (const file of fileNames) {
  // check if has matching slug; its based on filename, so we can already save a single file read here as well
  // read file content
  // check if has matching tags
  // add to array only if made it here
}
posts.sort(sortingFn);
return posts.slice(0, limit);
```

File: apps/www/pages/blog/[slug].tsx [hunk 1]
```diff
@@ -29,16 +72,21 @@ export async function getStaticPaths() {
   }
 }
 
-export async function getStaticProps({ params }: any) {
-  const filePath = `${params.slug}`
+export const getStaticProps: GetStaticProps<BlogPostPageProps, Params> = async ({ params }) => {
+  const filePath = `${params?.slug}`
```
Comment (gregnr) [inline apps/www/pages/blog/[slug].tsx:76]: Perhaps it'd be better to `throw` or return empty if `params` was undefined vs. silently fail.

Comment (ddanielcruzz) [reply apps/www/pages/blog/[slug].tsx]: Done, I decided to `throw`

**Comment by ddanielcruzz** [comment]
@kamilogorek Since I'm already working on this, I thought of applying your optimization instead of leaving it for later. Let me know if you encounter any bugs or issues. Thank you so much again for your feedback!

File: apps/www/pages/blog/[slug].tsx [hunk 2]
```diff
@@ -55,7 +107,7 @@ export async function getStaticProps({ params }: any) {
       nextPost: currentIndex === allPosts.length ? null : nextPost ? nextPost : null,
       relatedPosts,
       blog: {
-        slug: `${params.slug}`,
+        slug: `${params?.slug}`,
```
Comment (gregnr) [inline apps/www/pages/blog/[slug].tsx:110]: Since we know `params` should be defined by now:
```suggestion
        slug: `${params!.slug}`,
```

**Review by gregnr — COMMENTED** [review]
Nice work @ddanielcruzz, I appreciate the TS improvements

File: apps/www/pages/blog/[slug].tsx (hunk 2 above)
Comment (kamilogorek) [reply apps/www/pages/blog/[slug].tsx:110]: This can be removed entirely I believe, as `params?.slug === undefined` discriminate the type.

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBvRAHAhgJ1wFsBnRAXwC5Es9DSB+arEgGxAHMnESp8YwHChQCUNAFCIpiGMERo6xEgwB0bTogC82xOAAmAU2ACDesRknSr+A1BD4wlqeXFPEEBL0QB3XFC04BEpq7BxuAPThVgB6DOLkQA

Comment (gregnr) [reply apps/www/pages/blog/[slug].tsx:110]: Yep! My bad, I mistakenly thought we were in another scope (eg. `map()`). Good catch.

**Comment by MartinPELCAT** [comment]
Based on what @kamilogorek said, wouldn’t it be nice to verify if the length of post is already at the limit so that you can skip the unnecessary iterations?

**Comment by kamilogorek** [comment]
Unfortunately, you cannot push this _that far_, as you want to retrieve the latest N posts, which forces you to sort them first.

**Comment by MartinPELCAT** [comment]
> Unfortunately, you cannot push this _that far_, as you want to retrieve the latest N posts, which forces you to sort them first.

How about if you go through the list in reverse? The filesystem should have this list already ordered no? Since the date is stored at the beginning of the filename

**Comment by kamilogorek** [comment]
If that would be the case then sure, but here, `published_at` is extracted from the frontmatter metadata inside the file content.

File: apps/www/lib/posts.tsx [hunk 3]
```diff
@@ -9,45 +9,60 @@ type Directories = '_blog' | '_case-studies' | '_customers' | '_alternatives'
...
-  directory: Directories,
-  limit?: number,
-  tags?: any,
-  runner?: any
-) => {
+type GetSortedPostsParams = {
+  directory: Directories
+  limit?: number
+  tags?: string[]
+  runner?: unknown
```
[the remark this answers is not in the document]
Comment (ddanielcruzz) [reply apps/www/lib/posts.tsx:16]: It was in the previous version of the function (unused too), but I don't know if there are plans to use that down the road. That's why I didn't remove it.

**Comment by ddanielcruzz** [comment]
Hey @gregnr is there anything missing to merge this PR? 😄

**Review by kamilogorek — APPROVED** [review]

File: apps/www/pages/blog/[slug].tsx [hunk 4]
```diff
@@ -10,14 +11,56 @@ import { Badge, Divider, IconChevronLeft } from 'ui'
...
+  date: string
+  toc_depth?: number
+  author: string
+  image?: string
+  thumb?: string
+  youtubeHero?: string
+  author_url?: string
+  launchweek?: number
+  meta_title?: string
+  meat_description?: string
```
Comment (saltcod) [inline apps/www/pages/blog/[slug].tsx:37]:
```suggestion
  meta_description?: string
```

**Review by saltcod — APPROVED** [review]
