### PR TITLE
fix: copy cell for record peak portal on forgien relationship

### LINKED ISSUE #37454: Copying cell content of referencing cell copies copies wrong content
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I click on "View referencing record" in a column with a Foreign Key, I then can select a column of this referenced record and "Copy cell content" but it copies the content from the initial cell, not the referenced one.

## To Reproduce

1. Go to 'Table Editor'
2. Open a table with a foreign key
3. Click on the arrow "View referencing record" of a row
4. Right click and click "Copy cell content" on a cell from this referenced record preview

## Expected behavior

Should copy the content of the referenced record

## Screenshots

https://github.com/user-attachments/assets/2e6b1337-8ba7-4491-8e0a-990736745508

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: NA
- Version of Node.js: NA

### PR DESCRIPTION
**Pull request by awaseem**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES/NO

## What kind of change does this PR introduce?

fixes: #37454 

The context menu on the FK row is a lie, its just exposing the cell underneath. Ideally this should have its own context menu, right now we only support copy operations.

### CODE REVIEW

File: apps/studio/components/grid/components/formatter/ReferenceRecordPeek.tsx [hunk 1]
```diff
@@ -103,32 +134,51 @@ export const ReferenceRecordPeek = ({ table, column, value }: ReferenceRecordPee
...
-                <p className="text-foreground-light">
-                  Failed to find referencing row: {error.message}
-                </p>
-              )}
-              {isSuccess && <p className="text-foreground-light">No results were returned</p>}
-            </div>
-          ),
-        }}
-      />
+      <ContextMenu_Shadcn_>
```
Comment (joshenlim) [inline apps/studio/components/grid/components/formatter/ReferenceRecordPeek.tsx]: hmm a little odd to wrap the entire data grid in a context menu trigger
we typically do this at the cell level - which will then do away the need for a `useRef`

Comment (joshenlim) [reply apps/studio/components/grid/components/formatter/ReferenceRecordPeek.tsx]: yeah this leads to some odd behaviour where i can right click on an empty state and still see the copy cell context menu

**Review by joshenlim — APPROVED** [review]
Verified changes on preview!
