### PR TITLE
fix: update queries for local edge function and cron logs

### LINKED ISSUE #33549: Studio: 502 error for cron or edge functions logs on localhost
**Describe the bug**
Error 502 is shown when trying to view logs for cron or edge functions. All other types of logs work as expected.
Error `ERROR 42703 (undefined_column) column "body" does not exist` appears in logflare logs (see below).

**To Reproduce**
1. Follow steps from thread on [similar issue](https://github.com/supabase/supabase/issues/26785#issuecomment-2255463012)
2. Open Supabase Studio in browser
3. Go to log section "Cron" or "Edge Functions"

```json
{
  "code": 502,
  "errors": [],
  "message": "Something went wrong! Unknown error. If this continues please contact support.",
  "status": "UNKNOWN"
}
```

**Expected behavior**
Logs are shown.

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: -
 - Version of OS: MacOS 14.5
 - Version of CLI:  2.9.6 or 2.9.7 (beta)
 - Version of Docker: 27.4.0, build bde2b89
 - Versions of services: (for CLI v2.9.6) 

**Additional context**
If applicable, add any other context about the problem here.
 - Browser: Version 1.74.50 Chromium: 132.0.6834.111
 - similar issue on self-hosted env: https://github.com/supabase/supabase/issues/26309
- Error message in docker log from `supabase/logflare:1.4.0`:

<details>

<summary>log</summary>

```
2025-01-30 11:46:55 
2025-01-30 11:46:55 10:46:55.566 [error] GenServer {Logflare.Endpoints.Cache, 1, %{"iso_timestamp_start" => "2025-01-30T09:00:00.000Z", "project" => "default", "project_tier" => "ENTERPRISE", "ref" => "default", "sql" => "select id, function_edge_logs.timestamp, event_message, response.status_code, request.method, m.function_id, m.execution_time_ms, m.deployment_id, m.version from function_edge_logs\n  cross join unnest(metadata) as m\n  cross join unnest(m.response) as response\n  cross join unnest(m.request) as request\n  \n  order by timestamp desc\n  limit 100\n  "}} terminating
2025-01-30 11:46:55 ** (Postgrex.Error) ERROR 42703 (undefined_column) column "body" does not exist
2025-01-30 11:46:55 
2025-01-30 11:46:55     query: WITH retention AS (SELECT (CASE WHEN $1::text = 'FREE' THEN current_timestamp - INTERVAL '1 day' WHEN $2::text = 'PRO' THEN current_timestamp - INTERVAL '7 day' WHEN ($3::text = 'PAYG' OR $4::text = 'ENTERPRISE') THEN current_timestamp - INTERVAL '90 day' ELSE current_timestamp - INTERVAL '1 day' END) AS date), edge_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_7f013886_454c_40f7_b8f6_650df2c242ab" AS t WHERE (t.body ->> 'project') = $5::text AND CASE WHEN COALESCE($6::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($7::text AS TIMESTAMP) END AND CASE WHEN COALESCE($8::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) <= CAST($9::text AS TIMESTAMP) END AND CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > retention.date ORDER BY CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) DESC), postgres_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_1cbea6ce_f62e_4b72_8095_bfebf6606593" AS t WHERE (t.body ->> 'project') = $10::text AND CASE WHEN COALESCE($11::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($12::text AS TIMESTAMP) END AND CASE WHEN COALESCE($13::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) <= CAST($14::text AS TIMESTAMP) END AND CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > retention.date ORDER BY CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) DESC), function_edge_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_ea4f51a1_529a_4354_9086_aab422b217f0" AS t WHERE CASE WHEN COALESCE($15::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($16::text AS TIMESTAMP) END AND CASE WHEN COALESCE($17::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) <= CAST($18::text AS TIMESTAMP) END AND (body #>> '{metadata,project_ref}') = $19::text AND CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > retention.date ORDER BY CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) DESC), function_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_df00e22b_ae9a_4e4e_9ed6_c1e68c71dce5" AS t WHERE (body #>> '{metadata,project_ref}') = $20::text AND CASE WHEN COALESCE($21::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($22::text AS TIMESTAMP) END AND CASE WHEN COALESCE($23::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) <= CAST($24::text AS TIMESTAMP) END AND CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > retention.date ORDER BY CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) DESC), auth_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_fede7dae_3efb_4ed4_a757_00d7f4661784" AS t WHERE (t.body ->> 'project') = $25::text AND CASE WHEN COALESCE($26::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($27::text AS TIMESTAMP) END AND CASE WHEN COALESCE($28::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) <= CAST($29::text AS TIMESTAMP) END AND CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > retention.date ORDER BY CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) DESC), realtime_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_3759adf5_1d0f_4f8f_8cd8_3a70d717cb30" AS t WHERE (body #>> '{metadata,project}') = $30::text AND CASE WHEN COALESCE($31::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($32::text AS TIMESTAMP) END AND CASE WHEN COALESCE($33::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) <= CAST($34::text AS TIMESTAMP) END AND CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > retention.date ORDER BY CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) DESC), storage_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_b2553f6a_0d12_4deb_aa65_8adce117ffc1" AS t WHERE (body #>> '{metadata,project}') = $35::text AND CASE WHEN COALESCE($36::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($37::text AS TIMESTAMP) END AND CASE WHEN COALESCE($38::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) <= CAST($39::text AS TIMESTAMP) END AND CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > retention.date ORDER BY CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) DESC), postgrest_logs AS (SELECT (t.body -> 'timestamp') AS timestamp, (t.body -> 'id') AS id, (t.body -> 'event_message') AS event_message, (t.body -> 'metadata') AS metadata FROM retention, "_analytics"."log_events_43e56e0f_438d_496b_aed1_4758c5b6b258" AS t WHERE CASE WHEN COALESCE($40::text, '') = '' THEN true ELSE CAST((to_timestamp(CAST((t.body ->> 'timestamp') AS BIGINT) / 1000000.0) AT TIME ZONE 'UTC') AS TIMESTAMP) > CAST($41::text AS TIMESTAMP) END AND CASE WHEN COALESCE($42::text, '') (truncated)
2025-01-30 11:46:55 
2025-01-30 11:46:55 10:46:55.568 [error] Endpoint query exited for an unknown reason

```
</details>

### LINKED ISSUE #33834: Error while fetching Edge Functions Logs
Edge function logs is giving error.

Response of `api/platform/projects/default/analytics/endpoints/logs.all` API:

```json
{
    "error": {
        "code": 502,
        "errors": [],
        "message": "Something went wrong! Unknown error. If this continues please contact support.",
        "status": "UNKNOWN"
    }
}
```

## To Reproduce

1. Open Supabase Studio interface
2. Go to Logs > Edge Functions

## Screenshots

Image

## System information

- OS: macOS 15.3.1
- Version of Supabase CLI: 2.15.8

### LINKED ISSUE #36378: Logs & Analytics, Error fetching logs, 401 Unauthorized, Self-Hosting with Docker
Using the [Self-hosted using Docker](https://supabase.com/docs/guides/self-hosting/docker) instructions, observe the attached issue (401 Unauthorized) when navigating to the Logs & Analytics section in Studio. 

FYI, based on the title of the referenced issue below, it is not clear on why the previous issue was closed as the bug as stated does not seem to be addressed.

> 
> local docker-compose.yml snippet:
> ```
>   analytics:
>     container_name: supabase-analytics
>     image: supabase/logflare:1.14.2
> ```
> same as the [yaml in the repo](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml)
> 
> This docker image was built using the current version available and using instructions mentioned above. 
> 
> Image 

 _Originally posted by @pritish in [#34192](https://github.com/supabase/supabase/issues/34192#issuecomment-2968477866)_

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

Bug fix

## What is the new behavior?

Functions

Screenshot 2025-10-09 at 5 28 49 PM

Cron

Screenshot 2025-10-09 at 5 28 38 PM

## Additional context

Discussed with @Ziinc and agree that it's not ideal to have local function logs differ from hosted. But fixing the translation query in local logflare is more complex, so we can merge this as a stop gap.

closes https://github.com/supabase/supabase/issues/38121
closes https://github.com/supabase/supabase/issues/36378
closes https://github.com/supabase/supabase/issues/36378
closes https://github.com/supabase/supabase/issues/33834
closes https://github.com/supabase/supabase/issues/33549

### CODE REVIEW

**Comment by Ziinc** [comment]
closes https://github.com/supabase/supabase/issues/38121

**Comment by Ziinc** [comment]
Doing some verification checks before approval and merge

File: scripts/generateLocalEnv.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ const defaultEnv = {
   STUDIO_PG_META_URL: '$API_URL/pg',
   SUPABASE_PUBLIC_URL: '$API_URL',
   SENTRY_IGNORE_API_RESOLUTION_ERROR: '1',
-  LOGFLARE_URL: 'http://localhost:54329',
+  LOGFLARE_URL: 'http://127.0.0.1:54327',
```
Comment (mattrossman) [inline scripts/generateLocalEnv.js:26]: FYI in https://github.com/supabase/supabase/pull/39366 I also had to change `LOGFLARE_API_KEY` -> `LOGFLARE_PRIVATE_ACCESS_TOKEN` and upgrade the `supabase` CLI dep.

https://supabase.slack.com/archives/C0161K73J1J/p1759519589826339?thread_ts=1759511078.709489&cid=C0161K73J1J

**Review by joshenlim — APPROVED** [review]
Approving to unblock

**Review by avallete — APPROVED** [review]

**Comment by singh-inder** [comment]
Hi, just wanted to note that the edge function and cron logs still don’t show up in dashboard. I set up a new instance to double-check, but I’m seeing the same behavior. cc @aantti 

image

image


image

**Comment by sweatybridge** [comment]
Your studio version looks outdated. We have a PR to update https://github.com/supabase/supabase/pull/39468 but it's blocked on breaking change.

Meanwhile you may want to update it manually in the compose file yourself.

**Comment by singh-inder** [comment]
Tested with `supabase/studio:2025.10.09-sha-433e578` and `supabase/studio:2025.10.13-sha-6bb26fd` (latest release in dockerhub).

image



 Also tested with supabase cli v2.53.1:

image

image

**Comment by sweatybridge** [comment]
Cron logs also require you to update logflare as I explained here https://github.com/supabase/supabase/pull/39468#discussion_r2443383365

Edge functions logs should work with latest studio.

@singh-inder you can follow the cron logs progress here https://github.com/Logflare/logflare/pull/2846

**Comment by singh-inder** [comment]
So I tried with `supabase/logflare:1.23.0` and `supabase/studio:2025.10.13-sha-6bb26fd`. Still logs don't show up for both edge functions and cron. Just to be sure I even reset the db and setup a new cron job which calls function at 1 min interval. 

I'll wait for the logflare PR to be merged. Thanks!

**Comment by w0rmh0l3** [comment]
thank you @sweatybridge and @Ziinc - I can confirm the edge and cron logs now work!

@singh-inder - apart from manually updating the compose file with the newer container versions, you also need to update the vector.yml file to reflect the changes. [fix: vector config for function logs](https://github.com/supabase/supabase/pull/39388/commits/7c6c216da211eb65381a21cedb589e8db9c891e0)

**Comment by singh-inder** [comment]
@w0rmh0l3 Yes, I'm aware of changes in logs/vector.yml file and I tested after making those changes.
This logs issue was fixed with `supabase/studio:2025.10.20-sha-5005fc6` but this version broke storage uploads from self-hosted studio, so you should upgrade to `supabase/studio:2025.10.27-sha-85b84e0`
