### PR TITLE
Strip spaces from webhook url input

### LINKED ISSUE #9390: Empty spaces in webhooks HTTP request block insert and update on the table linked with the webhook
# Bug report

## Describe the bug
When creating a webhook, if by mistake you add an empty space on the HTTP request, this will block the associated table. Every time you try to add or update a row you'll get this message:
```
Failed to run sql query: URL using bad/illegal format or missing URL
``` 

## To Reproduce

1. Create a table (default settings)
2. Create an edge function
3. Create a webhook to watch insert and update on this table
4. Copy your edge function url
5. Paste the URL into the HTTP request of the webhook - This is where the mistake happen as there was an empty space before that I could not see.
6. Try adding a row on the new table
7. Error - "Failed to run sql query: URL using bad/illegal format or missing URL"
8. Remove the webhook
9. Try adding a row on the table again
10. It's now working.

## Expected behavior

To avoid having this mistake in the future a very simple fix could be to remove all spaces automatically when creating the webhook. Also perhaps there might be a better way to present the error as this one was really hard to track as it was not related to the table but to a webhook.

## Screenshots
CleanShot_2022-10-07_at_12 38 192x

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

### PR DESCRIPTION
**Pull request by saltcod**
Resolves: https://github.com/supabase/supabase/issues/9390

### CODE REVIEW

File: studio/components/interfaces/Database/Hooks/CreateHook/ServiceConfigForm/InputServiceUrl.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ const InputServiceUrl: FC = observer(({}) => {
       onChange={(e) =>
         _localState.onFormChange({
           key: 'serviceUrl',
-          value: e.target.value,
+          value: e.target.value.replaceAll(' ', ''),
```
Comment (joshenlim) [inline studio/components/interfaces/Database/Hooks/CreateHook/ServiceConfigForm/InputServiceUrl.tsx:20]: we shouldn't be stripping in `onChange` i think - we should just do this prior to saving
also, i'd reckon we just do a `trim` though. most of the fields in the dashboard where we remove whitespace is using trim, so just to keep things consistent.

Comment (joshenlim) [reply studio/components/interfaces/Database/Hooks/CreateHook/ServiceConfigForm/InputServiceUrl.tsx]: ahh okay yeah fair enough, not supposed to have spaces in the middle of URLs

**Review by joshenlim — APPROVED** [review]
