### PR TITLE
fix(local): Supabase Studio giving success message even if the delete user operation fails 

### LINKED ISSUE #16821: bug: Supabase Studio giving success message even if the delete user operation fails
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
 
Local Supabase Studio gives the success message even if the delete user operation fails. 
The cloud Supabase dashboard is working as expected.

## To Reproduce

Steps to reproduce the behavior,

You can intentionally create a DB schema that does not let the row in `auth.users` to directly delete.

1. Create a table that references `auth.users` table. Do not add cascade delele
2. Add some data that references one of the items in `auth.users` table.
3. Try deleting the user from the dashboard.
4. You will see a success message.
5. Reload the list of users, and you will see that the user is still in the list.

## Expected behavior

As this deletion was causing foreign key constraint violation. The success message should not come. Instead, an error message should come. 
## Screenshots

https://github.com/supabase/supabase/assets/41117038/398d94f6-8f39-42bb-a38e-936a3eba04b3

## System information

- OS: macOS
- Version of Node.js: 18.15.0

### LINKED ISSUE #16830: bug: Dashboard gets stuck if user deletion fails.
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you try to delete a user from the dashboard, and if the deletion fails for some reason, the confirmation popup does not go away, and the user can't interact with the page. The only option is refreshing the page from the browser/

## To Reproduce

1. Go to Auth Dashboard
2. Try deleting a user, that will cause an error
3. You see the error message, and the confirmation popup does not dismiss.

## Expected behavior

The confirmation popup should be dismissed if the deletion fails.

## Screenshots

https://github.com/supabase/supabase/assets/41117038/80f5fd3c-f747-494a-b117-08f5a11dafc6

## System information

- OS: macOS
- Browser: Arc (Chromium)

### PR DESCRIPTION
**Pull request by kishanhitk**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Fixes #16821
Also fixes: #16830

## What is the new behavior?

Now, the dashboard gives proper error message, if the operation fails.

## Additional context

Turns out this was simply a _missing `await`_ bug.

### CODE REVIEW

File: studio/components/interfaces/Auth/Users/UserDropdown.tsx [hunk 1]
```diff
@@ -82,8 +82,7 @@ const UserDropdown = ({ user, canRemoveUser, canRemoveMFAFactors }: UserDropdown
           ui.setNotification({ category: 'success', message: `Successfully deleted ${user.email}` })
           PageState.users = PageState.users.filter((x: any) => x.id != user.id)
           PageState.totalUsers -= 1
-        } finally {
-        }
+        } catch (error) {}
```
Comment (gharewal12) [inline studio/components/interfaces/Auth/Users/UserDropdown.tsx:85]: You should log the error in the catch block to address the error

**Review by alaister — APPROVED** [review]
LGTM! Thanks, @kishanhitk!
