### PR TITLE
fix: #38830

### LINKED ISSUE #38830: "Create Table" Widget is visible when viewing protected schemata
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The "Create a table" widget is visible in protected schemata.

## To Reproduce

1. Go to Table Editor
2. Choose a protected schema like the `auth` schema.

## Expected behavior

The same logic as the "viewing protected schema" info should be used to hide the widget (instead of show it).

## Screenshots

Image
<br><br>
Image
<br><br>
Image

### PR DESCRIPTION
**Pull request by yazan-abu-obaideh**
Check if scheme is protected when setting table editor actions

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

Yes

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Widget is shown even for protected schemas

## What is the new behavior?

Widget is only shown when the schemata is not protected

### CODE REVIEW

File: apps/studio/components/layouts/Tabs/NewTab.tsx [hunk 1]
```diff
@@ -55,16 +59,18 @@ export function NewTab() {
...
+          icon: <Table2 className="h-4 w-4 text-foreground" strokeWidth={1.5} />,
+          title: 'Create a table',
+          description: 'Design and create a new database table',
+          bgColor: 'bg-blue-500',
+          isBeta: false,
+          onClick: snap.onAddTable,
+        },
+      ]
 
   const sqlEditorActions = [
```
Comment (yazan-abu-obaideh) [inline apps/studio/components/layouts/Tabs/NewTab.tsx:181]: I don't think these need to be changed as well, but it's worth double checking

**Comment by awaseem** [comment]
@yazan-abu-obaideh Would you mind just resolving the merge conflicts and then pinging me! I can take a look after

**Comment by yazan-abu-obaideh** [comment]
Thanks for the feedback @awaseem!

Please let me know if anything else needs to be done :)

**Review by awaseem — APPROVED** [review]
Nice this is a great small change, thank you for your contribution 💚 

Tested on self hosted and preview
