### PR TITLE
bug: fix sign-in when returnTo=sign-in

### LINKED ISSUE #23665: Supabase dashboard login screen doesn't redirect after singin
# Bug report: Supabase dashboard login screen doesn't redirect after singin

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The [sign in](https://supabase.com/dashboard/sign-in?) often doesn't redirect you after clicking "Sign In", when signing in with email and password.

## To Reproduce

1. Go to [the signin page](https://supabase.com/dashboard/sign-in?)
2. Fill in your email and password in the fields
3. Click "Sign In"
4. Wait a few seconds
5. You should be redirected, but nothing happens
6. Click the "Sign In" again and see this error:
error-screenshot
saying that you're already logged in

## Expected behavior

It should redirect you to the [dashboard](https://supabase.com/dashboard/projects)

## System information

- OS: Windows
- Browser: chrome

## Additional context

This happens only with email and password login, not with oAuth. Also after you click the "Sign In" for the 3rd time, it usually works.

### PR DESCRIPTION
**Pull request by simonha9**
- default redirect to /projects instead

fix #23665 

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

yes

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

#23665 when `returnTo=sign-in` then signing in returns to the same page

## What is the new behavior?

`SigninLayout` now checks if `returnTo` is the same as the page it's already on and if it is then defaults to `/projects`

## Additional context

Add any other context or screenshots.

### CODE REVIEW

File: apps/studio/components/interfaces/SignIn/SignInForm.tsx [hunk 1]
```diff
@@ -52,8 +52,8 @@ const SignInForm = () => {
 
         toast.success(`Signed in successfully!`, { id: toastId })
         await queryClient.resetQueries()
-
-        router.push(getReturnToPath())
+        const returnTo = getReturnToPath()
+        router.push(returnTo !== '/sign-in' ? returnTo : '/projects')
```
Comment (alaister) [inline apps/studio/components/interfaces/SignIn/SignInForm.tsx:56]: I think this is a little easier to read the other way round 😅

```suggestion
        // since we're already on the /sign-in page, prevent redirect loops
        router.push(returnTo === '/sign-in' ? '/projects' : returnTo)
```

**Review by alaister — APPROVED** [review]
Thanks, @simonha9!
