### PR TITLE
fix: Breadcrumbs and titles on AccountLayout pages

### LINKED ISSUE #13659: [studio] Breadcrumbs in invalid state when going back to /projects route
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Breadcrumbs retain the last seen org and project even when going back to studio home page

## To Reproduce

1. Go to https://app.supabase.com/projects
2. Click on any project
3. Go back
4. Breadcrumb will be `<org>/<project>/projects`
5. On refreshing, breadcrumbs become `Supabase/Projects`

## Expected behavior

Breadcrumbs should be `Supabase/Projects` on the studio home

## Screenshots
Screenshot 2023-04-12 at 10 19 07 PM

## System information

- OS: macOS
- Browser: chrome
- Version of Node.js: 18

### PR DESCRIPTION
**Pull request by gitstart**
## What kind of change does this PR introduce?

Fixes https://github.com/supabase/supabase/issues/13659

## What is the current behavior?

Breadcrumbs is showing wrong on pages which are using AccountLayout after navigated back from /project/* pages

Screenshot at Apr 14 22-53-40

## What is the new behavior?

Hide org name and selected project name on LayoutHeader when project ref param is not set

Screenshot at Apr 14 22-54-53

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

File: studio/pages/account/me.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ const User: NextPageWithLayout = () => {
 
 User.getLayout = (page) => (
   <AccountLayout
-    title="Supabase"
+    title="Preferences"
```
Comment (gitstart) [inline studio/pages/account/me.tsx:25]: @joshenlim I updated these page titles, IMO it makes more sense than just "Supabase | Supabase" like current version. WDYT?

Comment (gitstart) [reply studio/pages/account/me.tsx:25]: cc @saltcod

File: studio/pages/projects.tsx [hunk 2]
```diff
@@ -38,7 +38,7 @@ const ProjectsPage: NextPageWithLayout = () => {
 
 ProjectsPage.getLayout = (page) => (
   <AccountLayout
-    title="Supabase"
+    title="Projects"
```
Comment (alaister) [inline studio/pages/projects.tsx:41]: Because the "Projects" page is the home page for the dashboard, maybe this should say "Dashboard" instead of "Projects".

cc @MindTomato

**Review by alaister — COMMENTED** [review]
Thanks, @gitstart! Looks good! Just one question about the projects page title:

File: studio/pages/projects.tsx (hunk 2 above)
Comment (gitstart) [reply studio/pages/projects.tsx:41]: Thanks @alaister Should I change `Projects` in `breadcrumbs` to `dashboard` too?

**Review by alaister — APPROVED** [review]
Thanks, @gitstart! 🙌🏻
