### PR TITLE
Fix: infinite re-render on table when computing foreign keys

### LINKED ISSUE #39833: Bug Add foreign keys
i cant select column 

Image

### PR DESCRIPTION
**Pull request by awaseem**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Bug fix for https://github.com/supabase/supabase/issues/39833

## What is the current behavior?

When loading the table editor, this is causing an infinite re-render because of the following:

- This .filter() call creates a new array reference on every single render
- Even if the actual data hasn't changed, foreignKeys is a brand new array each time
- React's useEffect uses shallow comparison on dependencies
- It sees foreignKeys as "different" on every render (new reference) and re-runs the effect

## What is the new behavior?

no more unused re-renders 🙈

### CODE REVIEW

File: apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/TableEditor/TableEditor.tsx [hunk 1]
```diff
@@ -141,14 +141,18 @@ export const TableEditor = ({
     (constraint) => constraint.type === CONSTRAINT_TYPE.PRIMARY_KEY_CONSTRAINT
   )
 
-  const { data: foreignKeyMeta, isSuccess: isSuccessForeignKeyMeta } =
+  const { data: foreignKeyMeta = [], isSuccess: isSuccessForeignKeyMeta } =
```
Comment (charislam) [inline apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/TableEditor/TableEditor.tsx:144]: Nit: Correct me if I'm wrong, but won't `[]` be a new instance every render, so the fallback empty array is never memoized in practice? It doesn't currently cause infinite rerender because of the way we have useEffects set up, but it could be a footgun since at first glance it _looks_ memoized

**Review by charislam — APPROVED** [review]
Verified fix works in preview

File: apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/TableEditor/TableEditor.tsx (hunk 1 above)
Comment (awaseem) [reply apps/studio/components/interfaces/TableGridEditor/SidePanelEditor/TableEditor/TableEditor.tsx:144]: You are right here, let me revert this small change back and post a new PR
