### PR TITLE
Fix/5778

### LINKED ISSUE #5778: empty column name state in FK adder [minor]
image

and on the left side of the arrow here:

image

### PR DESCRIPTION
**Pull request by joshenlim**
Resolves https://github.com/supabase/supabase/issues/5778
- Added empty state for column editor for when column has no name yet in the form
- Fixed foreign key selector component not showing updated foreign key config (as highlighted by hieu)

Empty state: will show "This column" until user starts typing into the name field
image

### CODE REVIEW

File: studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx [hunk 1]
```diff
@@ -213,7 +215,7 @@ const ColumnForeignKeyUpdated: FC<{
         <div className="flex items-center justify-between">
           <div className="space-y-2">
             <Typography.Text>
-              The foreign key relation will be <span className="text-green-500">updated</span> as
+              The foreign key relation will be <span className="text-green-1000">updated</span> as
```
Comment (MildTomato) [inline studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx:218]: text-brand-900 ?

**Review by MildTomato — CHANGES_REQUESTED** [review]
see above

File: studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx [hunk 2]
```diff
@@ -213,7 +215,7 @@ const ColumnForeignKeyUpdated: FC<{
         <div className="flex items-center justify-between">
           <div className="space-y-2">
             <Typography.Text>
-              The foreign key relation will be <span className="text-green-500">updated</span> as
+              The foreign key relation will be <span className="text-green-900">updated</span> as
```
Comment (MildTomato) [inline studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx:218]: did you just resolve that without changing it?
@joshenlim

Comment (MildTomato) [reply studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx:218]: `text-brand-900`

File: studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx [hunk 3]
```diff
@@ -125,14 +125,16 @@ const ColumnForeignKeyAdded: FC<{
       block
       icon={<IconLink />}
       title={
-        <div className="flex items-center justify-between text-scale-1100">
+        <div className="text-scale-1100 flex items-center justify-between">
           <div className="space-y-2">
             <span>
               The following foreign key relation will be{' '}
               <span className="text-green-900">added</span>:
```
Comment (MildTomato) [inline studio/components/interfaces/TableGridEditor/SidePanelEditor/ColumnEditor/ColumnForeignKey.tsx:132]: `text-brand-900`

**Review by MildTomato — DISMISSED** [review]
see comments :D

**Review by phamhieu — APPROVED** [review]
