### PR TITLE
fix: Clicking the action icon on storage UI, should not trigger the row click event

### LINKED ISSUE #10525: Clicking the action icon on storage UI, should not trigger the row click event
# Bug report

## Describe the bug

When you click on the action (3dots) icon, on the list of storage items, it triggers the row click event.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the storage on dashboard
2. Upload a few items
3. Click to view items in list mode
4. On the action column (last column), focus on the 3 dot action icon.
5. Notice that the row click event is triggered after the dropdown is closed or an item on it is clicked.

## Expected behavior

Row click event should not be triggered when we click on the action icon.

## Screenshots

https://user-images.githubusercontent.com/45232708/203922921-7da3621d-e656-4ae7-ae03-bfdb78c2b1de.mov

## System information

- OS: macOS
- Browser chrome

## Additional context

As a side effect of this behavior, the rename action does not work on directories when triggered from the action icon and not the context menu (Right click on the row).

### PR DESCRIPTION
**Pull request by gitstart**
## What kind of change does this PR introduce?

Fixes https://github.com/supabase/supabase/issues/10525

## What is the current behavior?

Clicking the action icon on the storage UI triggers the row-click event

## What is the new behavior?

When any action on the view more icon is clicked, the row-click event (select row event) is not triggered.
It also resolves  a bug that occurs when attempting to delete an un-opened folder.

## Steps to test

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the storage on the dashboard
2. Upload a few items
3. On the action column, click on the 3-dot action icon.
4. Then click on any action: `Copy URL, Rename, ...`
5. Notice that the click does not trigger the row-click event.

## Demo

https://user-images.githubusercontent.com/1501599/206129498-9910d43d-d69e-4d56-8347-b23d645f31a4.mov

### CODE REVIEW

File: studio/localStores/storageExplorer/StorageExplorerStore.js [hunk 1]
```diff
@@ -1176,7 +1176,7 @@ class StorageExplorerStore {
     const files = await this.getAllItemsAlongFolder(folder)
     await this.deleteFiles(files, isDeleteFolder)
 
-    const isFolderOpen = this.openedFolders[this.openedFolders.length - 1].name === folder.name
+    const isFolderOpen = this.openedFolders[this.openedFolders.length - 1]?.name === folder.name
```
Comment (MagnusHJensen) [inline studio/localStores/storageExplorer/StorageExplorerStore.js:1179]: I don't see why this line is changed?

Comment (gitstart) [reply studio/localStores/storageExplorer/StorageExplorerStore.js:1179]: This throws an error when you attempt to delete a closed folder (using the menu items on the list).
i.e With no folders opened, `this.openedFolders` would be an empty array, and `this.openedFolders[this.openedFolders.length - 1]` would be `undefined`, which throws and error when you try to access `.name` property of `undefined`.

**Review by saltcod — APPROVED** [review]

**Comment by gitstart** [comment]
This PR was pushed through [Gitstart](https://www.gitstart.com/), with contributions from @AJAkimana @raph941, @phunguyenmurcul.
